[tool.poetry]
name = "gradbench"
version = "0.0.0"
description = "Benchmark for differentiable programming across languages and domains."
authors = []
packages = [{ include = "gradbench", from = "python" }]

[tool.poetry.dependencies]
python = "^3.11"
autograd = "^1"
jax = "^0.4"
jaxlib = "^0.4"
numpy = "^1"
pydantic = "^2"
scipy = "^1"
tensorflow = "^2"
torch = "^2"

[tool.poetry.group.dev.dependencies]
black = "^24"
isort = "^5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
skip_gitignore = true
