[tool.poetry]
name = "gradbench"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
autograd = "^1"
jax = "^0.4"
jaxlib = "^0.4"
numpy = "^1"
scipy = "^1"
tensorflow = "^2"
torch = "^2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
