name: Space
runs:
  using: composite
  steps:
    - uses: AdityaGarg8/remove-unwanted-software@v3
      with:
        remove-dotnet: "true"
        remove-android: "true"
        remove-haskell: "true"
        remove-codeql: "true"
