EXECUTABLES=hello gmm ba lstm ht kmeans ode llsq det lse

CXX?=c++
CC?=cc
CFLAGS=-std=c++17 -O3 -Wall -I../../cpp
LDFLAGS=-lm

EXECUTABLES=hello gmm ba lstm ht kmeans ode llsq det lse

include ../../cpp/common.mk
