#!/usr/bin/env python3
#
# Based on the log files produces by 'gradbench', generates plots via
# matplotlib. Three kinds of plots are produced, each with a line per
# provided JSON file:
#
# * Absolute runtime of primal function.
#
# * Absolute runtime of differentiated function (specifics depend on
#   the eval; typically computing the full Jacobian).
#
# * Relative runtime of the differentiated function compared to the
#   primal, i.e., the overhead of AD.
#
# Used like:
#
# $ scripts/plot futhark.json pytorch.json finite.json manual.json tapenade.json

import argparse
import json
import sys

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt


def mean(xs):
    if len(xs) == 0:
        return 0
    else:
        return sum(xs) / len(xs)


def read_msgs(fname):
    try:
        l = []
        with open(fname, "r") as f:
            for line in f:
                l.append(json.loads(line))
        if len(l) % 2 != 0:
            print("{fname} contains an odd number of messages.")
            sys.exit(1)
        return list(zip(l[0::2], l[1::2]))
    except Exception as e:
        print(f"Failed to read {fname}:")
        print(e)
        sys.exit(1)


parser = argparse.ArgumentParser()
parser.add_argument("jsons", nargs="+")
args = parser.parse_args()

eval = None
jsons = {}
for fname in args.jsons:
    print(f"Reading {fname}...")
    jsons[fname] = read_msgs(fname)
    this_eval = jsons[fname][0][0]["message"]["eval"]
    if eval is None:
        eval = this_eval
        print(f'Detected eval: "{eval}".')
    elif this_eval != eval:
        print(f'{fname}: is a log for eval "{this_eval}", which differs from "{eval}".')
        sys.exit(1)

workloads = set()
primal_runtimes = {}
diff_runtimes = {}

primal = "objective"
diff = "jacobian"
if eval == "kmeans":
    primal = "cost"
    diff = "dir"

for json in jsons:
    print(f"Extrating measurements from {json}...")
    primal_runtimes[json] = {}
    diff_runtimes[json] = {}
    for e in jsons[json]:
        message = e[0]["message"]
        response = e[1]["response"]
        if message["kind"] == "evaluate":
            workload = message["description"]
            workloads.add(workload)
            if message["function"] == primal:
                primal_runtimes[json][workload] = (
                    mean(
                        [
                            x["nanoseconds"]
                            for x in response["timings"]
                            if x["name"] == "evaluate"
                        ]
                    )
                    / 1e9
                )
            if message["function"] == diff:
                diff_runtimes[json][workload] = (
                    mean(
                        [
                            x["nanoseconds"]
                            for x in response["timings"]
                            if x["name"] == "evaluate"
                        ]
                    )
                    / 1e9
                )

fname_primal = f"{eval}-primal.png"
print(f"Generating {fname_primal}...")
for tool in primal_runtimes:
    plt.plot(primal_runtimes[tool].keys(), primal_runtimes[tool].values(), label=tool)
plt.tick_params(labelrotation=45)
plt.legend()
plt.yscale("log")
plt.title(f"{eval} - {primal} runtimes")
plt.ylabel("Runtime (s)")
plt.xlabel("Workload")
plt.savefig(fname_primal, bbox_inches="tight")
plt.clf()

fname_diff = f"{eval}-diff.png"
print(f"Generating {fname_diff}...")
for tool in diff_runtimes:
    plt.plot(diff_runtimes[tool].keys(), diff_runtimes[tool].values(), label=tool)
plt.tick_params(labelrotation=45)
plt.yscale("log")
plt.legend()
plt.title(f"{eval} - {diff} runtimes")
plt.ylabel("Runtime (s)")
plt.xlabel("Workload")
plt.savefig(fname_diff, bbox_inches="tight")
plt.clf()

fname_diff_vs_primal = f"{eval}-diff-vs-primal.png"
print(f"Generating {fname_diff_vs_primal}...")
for tool in diff_runtimes:
    dif = np.array(list(diff_runtimes[tool].values()))
    obj = np.array(list(primal_runtimes[tool].values()))
    plt.plot(diff_runtimes[tool].keys(), dif / obj, label=tool)
plt.tick_params(labelrotation=45)
plt.yscale("log")
plt.legend()
plt.title(f"{eval} - {diff} ÷ {primal}")
plt.ylabel("Relative overhead")
plt.xlabel("Workload")
plt.savefig(fname_diff_vs_primal, bbox_inches="tight")
plt.clf()
