[package]
name = "gradbench-floretta"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
floretta = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasmtime = "29"
wat = "1"
