name: Delete branches
on:
  schedule:
    # same as the nightly workflow
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # https://stackoverflow.com/a/27393574
      - name: Track CI branches
        run: git remote set-branches origin 'ci/refs/pull/*/merge'
      - name: Checkout CI branches
        run: git fetch --depth=1
      # https://stackoverflow.com/q/3670355
      - name: Delete CI branches
        # we use a colon instead of `--delete`, in case there are zero
        run:
          git for-each-ref --format=':%(refname:lstrip=3)'
          'refs/remotes/origin/ci/refs/pull/*/merge' | xargs -d '\n' git push
          origin
