name: Nightly
on:
  schedule:
    # run daily at 1am UTC, just so nobody thinks it's yesterday or tomorrow
    - cron: "0 1 * * *"
  workflow_dispatch:

concurrency:
  group: nightly

permissions:
  contents: write
  packages: write

jobs:
  cli:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build CLI
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: x86_64-unknown-linux-musl
          args: --package=gradbench --profile=release-with-debug
      - name: Upload CLI as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli
          path: target/x86_64-unknown-linux-musl/release-with-debug/gradbench

  matrix:
    needs: cli
    runs-on: ubuntu-24.04
    outputs:
      date: ${{ steps.matrix.outputs.date }}
      eval: ${{ steps.matrix.outputs.eval }}
      tool: ${{ steps.matrix.outputs.tool }}
      run: ${{ steps.matrix.outputs.run }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install CLI from artifact
        uses: ./.github/actions/cli
      - name: Compute job parameters
        id: matrix
        run: gradbench repo matrix | tee -a "$GITHUB_OUTPUT"

  run:
    needs:
      - cli
      - matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.matrix.outputs.run) }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Increase disk space
        uses: ./.github/actions/space
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Install CLI from artifact
        uses: ./.github/actions/cli
      - name: Run
        id: run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gradbench repo run --check -o run --timeout 600 ${{ matrix.args }}
      - name: Upload log as artifact
        if: success() || steps.run.conclusion == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: run-${{ matrix.artifact }}
          path: run

  stats:
    needs:
      - cli
      - matrix
      - run
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install CLI from artifact
        uses: ./.github/actions/cli
      - name: Download all log artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run download ${{ github.run_id }} --dir artifacts --pattern 'run-*'
      - name: Flatten log directory structure
        run: gradbench log flatten artifacts -o run
      - name: Checkout nightly stats branch
        uses: actions/checkout@v4
        with:
          path: stats
          ref: ci/refs/heads/nightly
      - name: Delete contents of nightly stats branch dir
        continue-on-error: true
        working-directory: stats
        run: git rm -rf .
      - name: Generate stats
        env:
          DATE: ${{ fromJSON(needs.matrix.outputs.date) }}
        run: |
          gradbench repo stats run -o stats --date "$DATE" --commit "$GITHUB_SHA"
      - name: Upload stats as artifact
        uses: actions/upload-artifact@v4
        with:
          name: stats
          path: stats
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Commit and push nightly stats branch
        working-directory: stats
        env:
          DATE: ${{ fromJSON(needs.matrix.outputs.date) }}
        run: |
          git add .
          git commit --allow-empty -m "Nightly stats on $DATE for commit $GITHUB_SHA"
          git push -f origin HEAD
          git tag "nightly-$DATE"
          git push origin "nightly-$DATE"
      - name: Update nightly branch
        run: |
          git checkout -B nightly
          git push origin nightly --force
